### ISSUE TITLE
Detail view broken

### ISSUE THREAD

**Issue by stuartcusackie** [whitecube/nova-page#81] opened 2021-06-01 09:39 UTC
There seems to be a conflict between Nova v3.26.1 and NovaPage 0.2.7. Rolling back to Nova v.3.22.0 and NovaPage 0.2.6 solves the problem.

I've double checked everything in my code to make sure I'm not creating a conflict. I've re-published nova assets, manually added service providers and removed all of my code to test, but the problem remained. I'm pretty sure the problem is in the package.

**Clues:**

- The edit resource view still works for some reason.
- Visiting this route directly `http://homestead.test/nova-api/nova-page/actions` returns a 404, even though I can see it in my routes list, and adding it manually to my own routes file makes no difference. I don't understand why this route is not available.

**Error details:**

Pages index loads fine but there is a console error:
```
vendor.js?id=158eb2009eabe0a47c04:1 
GET http://homestead.test/nova-api/nova-page/actions?relationshipType=&display=index 404 (Not Found)
... at FtD3.t.exports
```

Clicking into the resource detail view gets stuck on the loading icon produces this console error:

```
vendor.js?id=158eb2009eabe0a47c04:1
GET http://homestead.test/nova-api/nova-page/actions?resourceId=route.home&editing=true&editMode=create&display=detail 404 (Not Found)
... at FtD3.t.exports
```

**Comment by MannikJ** [comment] 2021-07-07 11:32
Same issue here...

**Comment by TzoLy** [comment] 2021-07-07 18:40
Seems like a problem with ActionController::class from route /nova-api/nova-page/actions

**Comment by tjmckenzie** [comment] 2021-08-17 04:29
I am getting the same error. I noticed loaded 1 time, either right before or after switching to DB storage. Unable to reproduce it since.

**Comment by Nyratas** [comment] 2021-09-02 10:32
Could someone please test the current version of dev-master and check if everything works fine since I merged @thecaliskan's PR ? Thanks !

**Comment by stuartcusackie** [comment] 2021-09-02 17:14
@Nyratas Seems good to me after a quick local test. Detail view is working with the latest version of Nova. I'll be testing on a production server over the next week or two.

**Comment by thecaliskan** [comment] 2021-09-08 10:34
@Nyratas  new release ?

**Comment by Nyratas** [comment] 2021-09-09 09:53
Yes, I just published a new release. Thanks @thecaliskan!

**Closed by Nyratas** 2021-09-09 09:53 UTC
